# Generated by Django 3.1 on 2020-09-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostSMedia', '0004_auto_20200921_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_image',
        ),
    ]
