# Generated by Django 3.1 on 2020-09-26 12:48

import PostSMedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostSMedia', '0005_remove_post_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=PostSMedia.models.upload_path),
        ),
    ]
