# Generated by Django 3.1 on 2021-02-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSMedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_type',
        ),
    ]
