# Generated by Django 3.1 on 2021-05-18 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChatSMedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender_username',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='auth.user'),
            preserve_default=False,
        ),
    ]
