# Generated by Django 3.1 on 2021-02-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSMedia', '0004_auto_20210204_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
