# Generated by Django 3.1 on 2021-02-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSMedia', '0005_auto_20210204_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
    ]
