# Generated by Django 3.1 on 2021-05-30 13:40

import StorieSMedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorieSMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='expiration_date',
            field=models.DateTimeField(default=StorieSMedia.models.defaultTime),
        ),
    ]
