version: "3"

services:
    app:
        build: .
        depends_on:
            - db
            - redis
        container_name: monkeysmedia
        ports:
            - 8000:8000
            - 80:80
        command: >
            bash -c 
            "
            python manage.py makemigrations &&
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app

    db:
        image: postgres:12-alpine
        restart: always
        ports:
            - 5432:5432
        container_name: monkeysmedia_db
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=MonkeySMedia

    redis:
        image: redis:5
        ports:
            - 6379:6379


