# Generated by Django 3.1 on 2020-09-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileSMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_image',
            field=models.FileField(default='default/MonkeySMediaSystem.png', upload_to='profile-%d-%m-%Y'),
        ),
    ]
