# Generated by Django 3.1 on 2020-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileSMedia', '0002_auto_20200921_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='description',
            field=models.TextField(default='', max_length=800),
        ),
    ]
