# Generated by Django 3.1 on 2020-09-26 21:47

import ProfileSMedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileSMedia', '0004_profileuser_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_image',
            field=models.FileField(default='default/MonkeySMediaSystem.png', upload_to=ProfileSMedia.models.upload_path),
        ),
    ]
