# Generated by Django 3.1 on 2020-10-16 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfileSMedia', '0006_auto_20201003_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrelation',
            name='followers',
        ),
        migrations.AddField(
            model_name='followrelation',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProfileSMedia.profileuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower', through='ProfileSMedia.FollowRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
