# Generated by Django 3.1 on 2021-02-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileSMedia', '0016_auto_20210204_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_profileuser_followers_+', through='ProfileSMedia.FollowRelation', to='ProfileSMedia.ProfileUser'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_profileuser_following_+', to='ProfileSMedia.ProfileUser'),
        ),
    ]
