# Generated by Django 3.1 on 2021-02-06 20:24

import ProfileSMedia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfileSMedia', '0017_auto_20210206_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower', through='ProfileSMedia.FollowRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='profile_image',
            field=models.FileField(default='default/face_img/1.svg', upload_to=ProfileSMedia.models.upload_path),
        ),
    ]
